#c3p0 config
c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/springboot_edu?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  user: root
  password: root
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false